version: '3'
services:
  frontend:
    build: ./client
    ports:
      - 3000:3000
    container_name: datagrid_frontend
    env_file:
      - ./client/.env
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - 1337:1337
    container_name: datagrid_backend
    env_file:
      - ./server/.env
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: datagrid_database
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./database/.env

volumes:
  db_data:
